HEARTBEAT = "0"
TESTREQUEST = "1"
RESENDREQUEST = "2"
REJECT = "3"
SEQUENCERESET = "4"
LOGOUT = "5"
IOI = "6"
ADVERTISEMENT = "7"
EXECUTIONREPORT = "8"
ORDERCANCELREJECT = "9"
LOGON = "A"
NEWS = "B"
EMAIL = "C"
NEWORDERSINGLE = "D"
NEWORDERLIST = "E"
ORDERCANCELREQUEST = "F"
ORDERCANCELREPLACEREQUEST = "G"
ORDERSTATUSREQUEST = "H"
ALLOCATION = "J"
LISTCANCELREQUEST = "K"
LISTEXECUTE = "L"
LISTSTATUSREQUEST = "M"
LISTSTATUS = "N"
ALLOCATIONINSTRUCTIONACK = "P"
DONTKNOWTRADE = "Q"
QUOTEREQUEST = "R"
QUOTE = "S"
SETTLEMENTINSTRUCTIONS = "T"
MARKETDATAREQUEST = "V"
MARKETDATASNAPSHOTFULLREFRESH = "W"
MARKETDATAINCREMENTALREFRESH = "X"
MARKETDATAREQUESTREJECT = "Y"
QUOTECANCEL = "Z"
QUOTESTATUSREQUEST = "A"
QUOTEACKNOWLEDGEMENT = "B"
SECURITYDEFINITIONREQUEST = "C"
SECURITYDEFINITION = "D"
SECURITYSTATUSREQUEST = "E"
SECURITYSTATUS = "F"
TRADINGSESSIONSTATUSREQUEST = "G"
TRADINGSESSIONSTATUS = "H"
MASSQUOTE = "I"
BUSINESSMESSAGEREJECT = "J"
BIDREQUEST = "K"
BIDRESPONSE = "L"
LISTSTRIKEPRICE = "M"

sessionMessageTypes = [HEARTBEAT, TESTREQUEST, RESENDREQUEST, REJECT, SEQUENCERESET, LOGOUT, LOGON]

tags = {}
for x in dir():
    tags[str(globals()[x])] = x

def msgTypeToName(n):
    try:
        return tags[n]
    except KeyError:
        return str(n)